# Default setup is given for MySQL with ruby1.9. If you're running Redmine
# with MySQL and ruby1.8, replace the adapter name with `mysql`.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).

production:
  adapter: mysql2
  database: gp
  host: localhost
  username: noelia
  password: "root"
  encoding: utf8

development:
  adapter: mysql2
  database: gp
  host: localhost
  username: noelia
  password: "root"
  encoding: utf8
